<?php
$displayName = escape((string) ($currentUser['full_name'] ?? 'Student'));
$initial = escape(strtoupper(substr(trim((string) ($currentUser['full_name'] ?? 'S')), 0, 1)));
$moodDetails = ['excellent' => ['😊', 'Excellent', 'positive'], 'good' => ['🙂', 'Good', 'positive'], 'neutral' => ['😐', 'Neutral', ''], 'stressed' => ['😔', 'Stressed', 'low'], 'overwhelmed' => ['😢', 'Overwhelmed', 'low']];
$trendScores = array_column($summary['trend'], 'score');
$hasTrend = count(array_filter($trendScores, static fn($score): bool => $score !== null)) > 0;
?>
<main class="student-app wellness-app"><div class="dashboard-glow glow-one" aria-hidden="true"></div><div class="dashboard-glow glow-two" aria-hidden="true"></div>
    <?php $activePage = 'checkin_history'; require APP_ROOT . '/views/layouts/app-sidebar.php'; ?>
    <section class="dashboard-content">
        <?php $topbarTitle = 'Wellness History'; require APP_ROOT . '/views/layouts/dashboard-topbar.php'; ?>
        <section class="history-heading"><div><p class="section-kicker">YOUR WELLBEING, OVER TIME</p><h1>Wellness history</h1><p>A gentle view of your check-ins. Notice patterns, not perfection.</p></div><a class="new-checkin" href="index.php?page=checkin">＋ New check-in</a></section>
        <?php if (!empty($successMessage)): ?><p class="history-success" role="status"><?= escape($successMessage) ?></p><?php endif; ?>
        <section class="history-summary"><article class="history-score glass-surface"><div><span class="summary-icon green">✦</span><p>Average wellbeing</p></div><strong><?= $summary['average'] ?? '—' ?><span>/100</span></strong><small>from your last 7 days</small></article><article class="history-score glass-surface"><div><span class="summary-icon blue">⌁</span><p>Check-ins completed</p></div><strong><?= $summary['week_count'] ?><span>/7</span></strong><small>days this week</small></article><article class="history-score glass-surface"><div><span class="summary-icon orange">♨</span><p>Current streak</p></div><strong><?= $summary['streak'] ?><span> day<?= $summary['streak'] === 1 ? '' : 's' ?></span></strong><small>consecutive check-in<?= $summary['streak'] === 1 ? '' : 's' ?></small></article></section>
        <section class="history-chart glass-surface"><div class="chart-header"><div><p class="section-kicker">WELLBEING TREND</p><h2>Your last 7 days</h2></div></div><?php if ($hasTrend): ?><div class="chart-key"><span><i></i> Daily wellness score</span><em>Based on your saved check-ins</em></div><div class="trend-bars"><?php foreach ($summary['trend'] as $day): ?><div><span class="trend-value"><?= $day['score'] ?? '—' ?></span><i style="--score: <?= $day['score'] ?? 0 ?>%"></i><small><?= escape($day['label']) ?><b><?= escape($day['day']) ?></b></small></div><?php endforeach; ?></div><?php else: ?><div class="empty-history"><span>✦</span><h3>Your trend will appear here</h3><p>Complete your first check-in to start building your wellness history.</p><a href="index.php?page=checkin">Start a check-in →</a></div><?php endif; ?></section>
        <section class="history-lower"><article class="recent-checkins glass-surface"><div class="section-heading"><div><p class="section-kicker">RECENT CHECK-INS</p><h2>Your reflections</h2></div></div><?php if ($checkins): ?><div class="checkin-list"><?php foreach ($checkins as $checkin): $detail = $moodDetails[$checkin['mood']] ?? ['•', 'Check-in', '']; ?><article><span class="date-tile"><b><?= date('d', strtotime($checkin['created_at'])) ?></b><small><?= strtoupper(date('M', strtotime($checkin['created_at']))) ?></small></span><span class="list-mood"><?= $detail[0] ?></span><div><strong><?= escape($detail[1]) ?></strong><p><?= $checkin['comment'] !== '' ? '“' . escape($checkin['comment']) . '”' : 'No reflection added.' ?></p></div><em class="score-pill <?= $detail[2] ?>"><?= WellnessCheckin::scoreForMood($checkin['mood']) ?></em></article><?php endforeach; ?></div><?php else: ?><div class="empty-history compact"><span>♡</span><h3>No check-ins yet</h3><p>Your private reflections will appear here after your first check-in.</p></div><?php endif; ?></article></section>
    </section>
</main>
